/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ItemController;
import controller.PurchaseOrderController;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ItemModel;
import model.PurchaseOrderDetailsModel;
import model.PurchaseOrderModel;

/**
 *
 * @author Poshitha Ravindu
 */
public class POManagement extends javax.swing.JFrame {
    private double tot=0;
    private double itemtot=0;
    String itemNo; 
    private ItemModel item;
    private ArrayList<ItemModel> items;
    private ArrayList<PurchaseOrderDetailsModel> pList;
    /**
     * Creates new form AddPurchaseOrder
     */
    public POManagement() {
        initComponents();
         pList=new ArrayList<>();
        pIdTxt.setText(PurchaseOrderController.creatNewId());
        loadAllPurchases();
        setDate();
        loadItemsCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        itemTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pIdTxt = new javax.swing.JTextField();
        pDateTxt = new javax.swing.JTextField();
        uPriceTxt = new javax.swing.JTextField();
        itemQtyTxt = new javax.swing.JTextField();
        itemIdCmb = new javax.swing.JComboBox<>();
        addItemBtn = new javax.swing.JButton();
        deleteItemBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        purTbl = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailsTbl = new javax.swing.JTable();
        afsds = new javax.swing.JLabel();
        ototTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase Order Management");

        itemTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item No", "Item Name", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(itemTbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Purchase Order Management");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Purchase Id");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Purchase Date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Item Id");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Unit Price");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quantity");

        pIdTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pIdTxtActionPerformed(evt);
            }
        });

        pDateTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        uPriceTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        itemQtyTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemQtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemQtyTxtActionPerformed(evt);
            }
        });
        itemQtyTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemQtyTxtKeyReleased(evt);
            }
        });

        itemIdCmb.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemIdCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemIdCmbItemStateChanged(evt);
            }
        });
        itemIdCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdCmbActionPerformed(evt);
            }
        });

        addItemBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        addItemBtn.setText("Add Item");
        addItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addItemBtnActionPerformed(evt);
            }
        });

        deleteItemBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteItemBtn.setText("Delete Item");
        deleteItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("View Details");

        purTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PurchaseOrderID", "Date", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        purTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                purTblMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(purTbl);

        detailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "QTY", "Item Total"
            }
        ));
        jScrollPane3.setViewportView(detailsTbl);

        afsds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        afsds.setText("Item Total");

        ototTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ototTxt.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        ototTxt.setText("0.00");
        ototTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ototTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteItemBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(afsds))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ototTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(itemQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(pIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(itemIdCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(itemQtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ototTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(afsds))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deleteItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pIdTxtActionPerformed

    private void addItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addItemBtnActionPerformed
        DefaultTableModel dtm=(DefaultTableModel)itemTbl.getModel();
        
        dtm.addRow(new Object[]{item.getItemId(),item.getDesc(),itemQtyTxt.getText(),itemtot});
        tot=(Double.parseDouble(uPriceTxt.getText()) * Double.parseDouble(itemQtyTxt.getText()))+tot;
        ototTxt.setText(Double.toString(tot));
        pList.add(new PurchaseOrderDetailsModel(pIdTxt.getText(),item.getItemId(),Integer.parseInt(itemQtyTxt.getText()),itemtot));
        itemQtyTxt.setText("");
        ototTxt.setText("0.00");
    }//GEN-LAST:event_addItemBtnActionPerformed
    
    private void getSelectedItem(){
        String key=itemIdCmb.getSelectedItem().toString();
        
        for(ItemModel it:items){
            if(it.getDesc().equals(key)){
                item=new ItemModel(it.getItemId(),it.getDesc(),it.getBuyPrice(),it.getSellPrice(),it.getQty());
            }
        }
    }
    
    private void deleteItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemBtnActionPerformed
 DefaultTableModel model =(DefaultTableModel) itemTbl.getModel();
 try{
     int SelectedRowIndex = itemTbl.getSelectedRow();
     model.removeRow(SelectedRowIndex);
     
 }
 catch (ArrayIndexOutOfBoundsException  ex){}
 
    }//GEN-LAST:event_deleteItemBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
    clearall();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
            itemNo =itemIdCmb.getSelectedItem().toString();
            
            if(itemTbl.getRowCount()>0){
                if(PurchaseOrderController.addNewPurchaseOrder(new PurchaseOrderModel(pIdTxt.getText(), pDateTxt.getText(), tot,pList))){
                    JOptionPane.showMessageDialog(this, "Purchase Order Created Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                    loadAllPurchases();
                }
                newPOrder();
            }else{
                JOptionPane.showMessageDialog(this, "No Items In the Order. Please Add Several Items And Try Again.", "Order Empty", JOptionPane.INFORMATION_MESSAGE);
            }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void itemIdCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdCmbActionPerformed
        getItem();
        uPriceTxt.setText(Double.toString(item.getSellPrice()));
        itemQtyTxt.setText("");
         itemQtyTxt.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdCmbActionPerformed

    private void itemIdCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemIdCmbItemStateChanged
        getSelectedItem();
        uPriceTxt.setText(Double.toString(item.getSellPrice()));
        itemQtyTxt.setText("");
        itemQtyTxt.requestFocus();
    }//GEN-LAST:event_itemIdCmbItemStateChanged

    private void itemQtyTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemQtyTxtKeyReleased
        itemtot=(Double.parseDouble(uPriceTxt.getText()) * Double.parseDouble(itemQtyTxt.getText()));
        ototTxt.setText(Double.toString(itemtot));
    }//GEN-LAST:event_itemQtyTxtKeyReleased

    private void purTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_purTblMouseClicked
        
        try {
            int row=purTbl.rowAtPoint(evt.getPoint());
            String key=purTbl.getValueAt(row,0).toString();
            DefaultTableModel dtm=(DefaultTableModel)detailsTbl.getModel();
            ArrayList<PurchaseOrderDetailsModel> list=PurchaseOrderController.getAllDetails(key);
            dtm.setRowCount(0);
            for(PurchaseOrderDetailsModel pom:list){
                dtm.addRow(new Object[]{pom.getItemId(),pom.getQty(),pom.getItemTot()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(POManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(POManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
           
    }//GEN-LAST:event_purTblMouseClicked

    private void ototTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ototTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ototTxtActionPerformed

    private void itemQtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemQtyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemQtyTxtActionPerformed
     private void newPOrder(){
        DefaultTableModel dtm=(DefaultTableModel) itemTbl.getModel();
        dtm.setRowCount(0);
        pList=new ArrayList<>();
        pIdTxt.setText(PurchaseOrderController.creatNewId());
        setDate();
        loadItemsCombo();
        itemQtyTxt.setText("");
        tot=0;
        itemtot=0;
    }
      public void setDate(){
        SimpleDateFormat smdf = new SimpleDateFormat("yyyy-MM-dd hh:mm:ss");
        String date = smdf.format(new Date());
        pDateTxt.setText(date);
    }
        private void loadItemsCombo(){
        try {
            items=ItemController.getAllItems();
            
            for(ItemModel item:items){
                itemIdCmb.addItem(item.getDesc());
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        private void getItem(){
        String key=itemIdCmb.getSelectedItem().toString();
        
        for(ItemModel it:items){
            if(it.getDesc().equals(key)){
                item=new ItemModel(it.getItemId(),it.getDesc(),it.getBuyPrice(),it.getSellPrice(),it.getQty());
            }
        }
    }
private void clearall(){
    itemIdCmb.setSelectedIndex(0);
    uPriceTxt.setText("");
    itemQtyTxt.setText("");
    
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POManagement().setVisible(true);
            }
        });
    }
    
    private void loadAllPurchases(){
        try {
            ArrayList<PurchaseOrderModel> list=PurchaseOrderController.getAllPOs();
            DefaultTableModel dtm=(DefaultTableModel)purTbl.getModel();
            dtm.setRowCount(0);
            for(PurchaseOrderModel pom:list){
                dtm.addRow(new Object[]{pom.getpOrderId(),pom.getpOrderDate(),pom.getpOrderTot()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(POManagement.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(POManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addItemBtn;
    private javax.swing.JLabel afsds;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteItemBtn;
    private javax.swing.JTable detailsTbl;
    private javax.swing.JComboBox<String> itemIdCmb;
    private javax.swing.JTextField itemQtyTxt;
    private javax.swing.JTable itemTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField ototTxt;
    private javax.swing.JTextField pDateTxt;
    private javax.swing.JTextField pIdTxt;
    private javax.swing.JTable purTbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField uPriceTxt;
    // End of variables declaration//GEN-END:variables
}
